ALTER TABLE public.listings 
ADD COLUMN IF NOT EXISTS cause TEXT,
ADD COLUMN IF NOT EXISTS impact TEXT,
ADD COLUMN IF NOT EXISTS ways_to_give TEXT,
ADD COLUMN IF NOT EXISTS volunteering TEXT,
ADD COLUMN IF NOT EXISTS visiting TEXT;